// Proxies authenticated GET requests to the PalGate API.
// Accepts POST with JSON body: { endpoint: string, token: string }
// The token is already generated by the client — this function just forwards it.

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { endpoint, token } = req.body || {};

  if (!endpoint || typeof endpoint !== 'string') {
    return res.status(400).json({ error: 'Missing endpoint' });
  }

  // Prevent path traversal
  if (endpoint.includes('..') || endpoint.startsWith('/')) {
    return res.status(400).json({ error: 'Invalid endpoint' });
  }

  try {
    const upstream = await fetch(
      `https://api1.pal-es.com/v1/bt/${endpoint}`,
      {
        method: 'GET',
        headers: {
          'Accept': '*/*',
          'Accept-Language': 'en-us',
          'Content-Type': 'application/json',
          'x-bt-token': token || ''
        }
      }
    );

    let data;
    try {
      data = await upstream.json();
    } catch {
      data = { raw: await upstream.text() };
    }

    return res.status(upstream.status).json(data);
  } catch (err) {
    return res.status(502).json({ error: err.message });
  }
}
